export const PRODUCT_NAME = 'Gaminus';
export const PRODUCT_TOKEN = 'gaminus';
export const PACKAGE_NAME = PRODUCT_TOKEN;
export const CLI_NAME = PRODUCT_TOKEN;
export const DATA_ROOT = '~/.gaminus';
export const SYSTEMD_SERVICE_NAME = 'gaminus.service';
export const URL_SCHEME = 'gaminus';
export const URL_SCHEME_URL = 'gaminus://';
export const ENVIRONMENT_PREFIX = 'GAMINUS_';
export const DESKTOP_APP_ID = 'app.gaminus.desktop';
export const ARTIFACT_PREFIX = 'gaminus-';
export const REPOSITORY_SLUG = 'devswha/gaminus';
export const REPOSITORY_URL = 'https://github.com/devswha/gaminus';
export const ISSUES_URL = 'https://github.com/devswha/gaminus/issues';
export const RELEASES_URL = 'https://github.com/devswha/gaminus/releases';
export const AUTHOR = 'devswha and Gaminus contributors';
export const NODE_ENGINE_RANGE = '>=22.22.2 <23 || >=24.15.0 <25';
